### ISSUE TITLE
Is this meant to be displayed?

### ISSUE THREAD

**Issue by olivia-banks** [rh-robotics/.github#1]
Is this meant to be displayed? Currently, it isn't, because `PROFILE` is in all capital letters.

**Comment by teowelton** [comment]
Yeah, it is supposed to be displayed..... I just updated it to use `profile` (lowercase) and it still hasn't fixed it, so that's not the issue.

**Comment by teowelton** [comment]
Nevermind! It works when viewing the organization as public not when you're a member, which is fine.
